version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - order-service
      - product-service
    environment:
      - NODE_ENV=production

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - SECRET_KEY=b079ec85d8f0714d909a122868bf8aa5410ab40f27f4a2fd14ab6d19f39ba988c41e32fa3ea2e7858a8289e1b3ae85b28cad8c91ef9a111e23e621976830a371
      - MONGODB_URI=mongodb+srv://shamodchamaththa:chamaththa123@cluster0.jbqtuwa.mongodb.net/learn_microservice?retryWrites=true&w=majority&appName=Cluster0

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb+srv://shamodchamaththa:chamaththa123@cluster0.jbqtuwa.mongodb.net/order_service?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=b079ec85d8f0714d909a122868bf8aa5410ab40f27f4a2fd14ab6d19f39ba988c41e32fa3ea2e7858a8289e1b3ae85b28cad8c91ef9a111e23e621976830a371
      - PORT=3002

  product-service:
    build: ./product-service
    ports:
      - "3003:3003"
    environment:
      - SECRET_KEY=b079ec85d8f0714d909a122868bf8aa5410ab40f27f4a2fd14ab6d19f39ba988c41e32fa3ea2e7858a8289e1b3ae85b28cad8c91ef9a111e23e621976830a371
      - MONGODB_URI=mongodb+srv://shamodchamaththa:chamaththa123@cluster0.jbqtuwa.mongodb.net/learn_microservice?retryWrites=true&w=majority&appName=Cluster0